defaults:
  - vehicle: cube_sat_6u
  - control/mpc: default
  - _self_ # Override order: defaults first, then this file

sim:
  dt: 0.01
  duration: 30.0

mission: "hover" # Simple default
env: "deep_space"
