name: "Sequencing Demo"
stages:
  - type: goto
    target: [2.0, 2.0, 0.0]
    hold_time: 5.0

  - type: orbit
    center: [0.0, 0.0, 0.0]
    radius: 3.0
    speed: 0.2
    duration: 30.0 # Orbit for 30 seconds

  - type: return
